= Preface

== Purpose

This document describes the syntax of the openEHR Archetype Query Language (AQL).

== Status

This specification is in the {spec_status} state. The latest development version of this document can be found at {openehr_query_aql}[{openehr_query_aql}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Original Source

The text of this specification was originally posted on the {openehr_wiki_root}/spaces/spec/pages/4915203/AQL-+Archetype+Query+Language[openEHR wiki^], and was used by the global openEHR community in that form.

== Tooling status

=== AQL features not yet supported

The following features are likely to be needed, but are not yet implemented in tools:

* `TOP`
* `XOR`. Currently `AND`, `OR`, `NOT`, `EXISTS` are supported in `WHERE` clause.
* functions are not supported.
* embedded query is not supported
* `ORDER BY`
* `TIMEWINDOW`

== Further discussions

The existing AQL grammar and syntax could be further enhanced in the following areas:

* Reduce the length of the query statement. The use of archetype path in AQL query makes the query lengthy and hard to read. Local variables with meaningful names that are assigned with path can be used to reduce the length of the query as well as improve readability of the query. One example is shown below:

--------
let $systolic_bp="data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude"
let $diastolic_bp="data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude"

SELECT
    obs/$systolic_bp, obs/$diastolic_bp
FROM
    EHR [ehr_id/value=$ehrUid] CONTAINS COMPOSITION [openEHR-EHR-COMPOSITION.encounter.v1]
        CONTAINS OBSERVATION obs [openEHR-EHR-OBSERVATION.blood_pressure.v1]
WHERE
    obs/$systolic_bp>= 140 OR obs/$diastolic_bp>=90
--------
