= Preface

== Purpose

This document describes the syntax of the openEHR Archetype Query Language (AQL).

== Status

This specification is in the {spec_status} state. The latest development version of this document can be found at {openehr_query_aql}[{openehr_query_aql}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Original Source

The text of this specification was originally posted on the {openehr_wiki_root}/spaces/spec/pages/4915203/AQL-+Archetype+Query+Language[openEHR wiki^], and was used by the global openEHR community in that form.

== Tooling status

=== AQL features not yet supported

The following features are likely to be needed, but are not yet implemented in tools:

* `TOP`
* `XOR`. Currently `AND`, `OR`, `NOT`, `EXISTS` are supported in `WHERE` clause.
* functions are not supported.
* embedded query is not supported
* `ORDER BY`
* `TIMEWINDOW`
